---
# Curl isn't installed, needed for tests

- name: Prepare
  hosts: all

  tasks:
    - name: sestatus before package
      become: true
      command: "sestatus"
      register: status_1
      ignore_errors: true

    - name: Install packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - curl
          - gnupg
          - ca-certificates
          - python3
          - sudo
          - bash
          - policycoreutils
          - selinux-basics
          - selinux-utils
        state: present

    - name: sestatus after install
      become: true
      command: "sestatus"
      register: status_2
      ignore_errors: true

    - name: Reboot
      ansible.builtin.reboot:

    - name: sestatus after reboot
      become: true
      command: "sestatus"
      register: status_3
      ignore_errors: true

    - name: display sestatus
      ansible.builtin.debug:
        msg:
          - "status before install packages: {{ status_1 }}"
          - "status after install packages: {{ status_2 }}"
          - "status after reboot: {{ status_3 }}"
