---
# Curl isn't installed, needed for tests

- name: Prepare
  hosts: all


  tasks:
    - name: Upgrade
      ansible.builtin.apt:
        upgrade: dist

    - name: Install packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - curl
          - gnupg
          - ca-certificates
          - python3
          - sudo
          - bash
        state: present
